apiVersion: v1
kind: Service
metadata:
  name: wave-orchestrator
  namespace: wave-orchestrator
  labels:
    app: wave
    component: orchestrator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: health
      port: 8001
      targetPort: health
      protocol: TCP
  selector:
    app: wave
    component: orchestrator

---
apiVersion: v1
kind: Service
metadata:
  name: wave-orchestrator-headless
  namespace: wave-orchestrator
  labels:
    app: wave
    component: orchestrator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: wave
    component: orchestrator
